version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  postgresdb:
    container_name: postgresdb
    image: postgres
    environment:
      - POSTGRES_USER=${ORDER_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${ORDER_DATABASE_PASSWORD}
      - POSTGRES_DB=fourlanchesorder
      - POSTGRES_HOST_AUTH_METHOD="trust"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${ORDER_DATABASE_USERNAME} -d fourlanchesorder'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./.docker-conf/data/posgresql:/var/lib/posgresql/data
    ports:
      - "5432:5432"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=${PAYMENT_DATABASE_BASE}
      - MONGO_INITDB_ROOT_USERNAME=${PAYMENT_DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PAYMENT_DATABASE_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - '27017:27017'
    volumes:
      - ./.docker-conf/data/mongodb:/data/db
  mysqldb:
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=${KITCHEN_DATABASE_PASSWORD}
      - MYSQL_DATABASE=fourlanches
      - MYSQL_USER=${KITCHEN_DATABASE_USERNAME}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - ./.docker-conf/data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
  order:
    image: felipemag/order-app:sha-7f64a0e
    container_name: order
    depends_on:
      postgresdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - POSTGRESQL_DATASOURCE_URL=${ORDER_POSTGRESQL_DATASOURCE_URL}
      - DATABASE_USERNAME=${ORDER_DATABASE_USERNAME}
      - DATABASE_PASSWORD=${ORDER_DATABASE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - QUEUE_EXCHANGE=${QUEUE_EXCHANGE}
      - QUEUE_ORDER_STATUS_NAME=${QUEUE_ORDER_STATUS_NAME}
      - QUEUE_PAYMENT_NAME=${QUEUE_PAYMENT_NAME}
      - QUEUE_PAYMENT_CANCEL_NAME=${QUEUE_PAYMENT_CANCEL_NAME}
      - QUEUE_KITCHEN_NAME=${QUEUE_KITCHEN_NAME}
      - QUEUE_KITCHEN_CANCEL_NAME=${QUEUE_KITCHEN_CANCEL_NAME}
    ports:
      - "8080:8080"
  payment:
    image: felipemag/payment-app:sha-b97236d
    container_name: payment
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - MONGO_CONNECTION_STRING=mongodb://${PAYMENT_DATABASE_USERNAME}:${PAYMENT_DATABASE_PASSWORD}@${PAYMENT_DATABASE_HOST}:27017/${PAYMENT_DATABASE_BASE}?authSource=admin
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - QUEUE_EXCHANGE=${QUEUE_EXCHANGE}
      - QUEUE_ORDER_STATUS_NAME=${QUEUE_ORDER_STATUS_NAME}
      - QUEUE_PAYMENT_NAME=${QUEUE_PAYMENT_NAME}
      - QUEUE_PAYMENT_CANCEL_NAME=${QUEUE_PAYMENT_CANCEL_NAME}
    ports:
      - '8081:8080'
  kitchen:
    image: felipemag/kitchen-app:sha-5dcab4c
    container_name: kitchen
    depends_on:
      mysqldb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - MYSQL_DATASOURCE_URL=${KITCHEN_MYSQL_DATASOURCE_URL}
      - DATABASE_USERNAME=${KITCHEN_DATABASE_USERNAME}
      - DATABASE_PASSWORD=${KITCHEN_DATABASE_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - QUEUE_EXCHANGE=${QUEUE_EXCHANGE}
      - QUEUE_ORDER_STATUS_NAME=${QUEUE_ORDER_STATUS_NAME}
      - QUEUE_IN_PREPARATION_NAME=${QUEUE_IN_PREPARATION_NAME}
      - QUEUE_FINISHED_NAME=${QUEUE_FINISHED_NAME}
      - QUEUE_ORDER_CANCEL_NAME=${QUEUE_ORDER_CANCEL_NAME}
    ports:
      - '8082:8080'
